from datetime import datetime
from enum import Enum
from typing import List, Optional, Dict, Any

from pydantic import BaseModel, Field

from app.schemas.intelligence import BaseIntelligenceModel, SeverityEnum
from app.domain.models.hazard import HazardType


class SignalSource(str, Enum):
    FLOOD_ENGINE = "flood_engine"
    WILDFIRE_ENGINE = "wildfire_engine"
    CHANGE_DETECTION_ENGINE = "change_detection_engine"
    EXTERNAL_PROVIDER = "external_provider"


class IntelligenceSignal(BaseModel):
    """
    An atomic intelligence signal produced by a specialized engine.
    """
    signal_id: str
    source: SignalSource
    hazard_type: HazardType
    severity: SeverityEnum
    confidence: float = Field(ge=0.0, le=1.0)
    affected_area_km2: float
    detected_at: datetime
    temporal_window: Optional[str] = None
    raw_score: float = Field(ge=0.0, le=100.0)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class CorrelatedHazard(BaseModel):
    """
    Represents a relationship where one hazard influences or amplifies another.
    """
    primary_signal_id: str
    secondary_signal_id: str
    relationship_type: str  # e.g., "amplifies", "precedes", "causes"
    correlation_confidence: float = Field(ge=0.0, le=1.0)
    description: str


class IntelligenceExplanation(BaseModel):
    """
    Human-readable reasoning generated by the Explainability Engine.
    """
    contributing_indicators: List[str]
    reasoning_summary: str
    confidence_explanation: str
    detected_environmental_changes: List[str]


class PrioritizedEvent(BaseModel):
    """
    An intelligence signal ranked against others.
    """
    signal: IntelligenceSignal
    priority_score: float = Field(ge=0.0, le=100.0)
    priority_rank: int


class ForecastWindow(BaseModel):
    """
    Future anomaly detection timeline.
    """
    start_time: datetime
    end_time: datetime
    predicted_trend: str
    anomaly_probability: float = Field(ge=0.0, le=1.0)


class IntelligenceAssessment(BaseIntelligenceModel):
    """
    The unified overarching intelligence document correlating multiple hazard signals.
    """
    assessment_id: str
    location_id: Optional[str] = None
    signals: List[IntelligenceSignal]
    correlations: List[CorrelatedHazard]
    prioritized_events: List[PrioritizedEvent]
    explainability: IntelligenceExplanation
    forecasts: List[ForecastWindow] = Field(default_factory=list)
