environment: "staging"

backend:
  replicaCount: 2

frontend:
  replicaCount: 2

ingress:
  hosts:
    - host: api-staging.aegis-earth.com
      paths:
        - path: /
          pathType: Prefix
          service: backend
    - host: staging.aegis-earth.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
